"""add user-id fk in task_status

Revision ID: ef631ba858dc
Revises: 6ae1ca8af027
Create Date: 2025-12-31 08:55:42.604433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef631ba858dc'
down_revision: Union[str, None] = '6ae1ca8af027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_task_status_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('task_status', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_status_user_id_user'), type_='foreignkey')

    # ### end Alembic commands ###
